# -*- coding: utf-8 -*-
"""Corruption.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aCaDUX7-LgspZoJLmfdQHh2dTvETbZMp
"""

!pip install selenium

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# # Add debian buster
# cat > /etc/apt/sources.list.d/debian.list <<'EOF'
# deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster.gpg] http://deb.debian.org/debian buster main
# deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster-updates.gpg] http://deb.debian.org/debian buster-updates main
# deb [arch=amd64 signed-by=/usr/share/keyrings/debian-security-buster.gpg] http://deb.debian.org/debian-security buster/updates main
# EOF
# 
# # Add keys
# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517
# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A
# 
# apt-key export 77E11517 | gpg --dearmour -o /usr/share/keyrings/debian-buster.gpg
# apt-key export 22F3D138 | gpg --dearmour -o /usr/share/keyrings/debian-buster-updates.gpg
# apt-key export E562B32A | gpg --dearmour -o /usr/share/keyrings/debian-security-buster.gpg
# 
# # Prefer debian repo for chromium* packages only
# # Note the double-blank lines between entries
# cat > /etc/apt/preferences.d/chromium.pref << 'EOF'
# Package: *
# Pin: release a=eoan
# Pin-Priority: 500
# 
# Package: *
# Pin: origin "deb.debian.org"
# Pin-Priority: 300
# 
# 
# Package: chromium*
# Pin: origin "deb.debian.org"
# Pin-Priority: 700
# EOF

!apt-get update
!apt-get install chromium chromium-driver
from selenium import webdriver
def web_driver():
    options = webdriver.ChromeOptions()
    options.add_argument("--verbose")
    options.add_argument('--no-sandbox')
    options.add_argument('--headless')
    options.add_argument('--disable-gpu')
    options.add_argument("--window-size=1920, 1200")
    options.add_argument('--disable-dev-shm-usage')
    driver = webdriver.Chrome(options=options)
    return driver

! pip install bs4
! pip install lxml
import requests
import re
import pandas as pd
import time
import random
from datetime import date, timedelta
import pandas as pd
from urllib.parse import urljoin
import requests
from bs4 import BeautifulSoup as soup
from urllib.parse import urljoin
from bs4 import BeautifulSoup as bs
from selenium.webdriver.common.by import By

!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q http://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz
!tar xf spark-3.1.1-bin-hadoop3.2.tgz
!pip install -q findspark

# Set environment
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.1-bin-hadoop3.2"

import findspark
findspark.init()
from pyspark.sql import SparkSession

spark_jars = '/content/drive/MyDrive/Colab_Notebooks/postgresql-42.2.14.jar'

def get_spark(master="local[*]",name='DataEng'):
  builder = SparkSession.builder.appName(name)
  builder.config("spark.jars",spark_jars)
  return builder.getOrCreate()

spark = get_spark()
print(f'spark_session:{spark.version}')

def class_select(driver,selector):
  info = driver.find_elements(By.CLASS_NAME,selector)
  return [info[i].text for i in range(len(info))]

# webscrape past 5 year's corruption data
def find_info(corruption_url):
  feature_names = ['country','rank','corrupt_score','year']
  corruption_table = pd.DataFrame(columns= feature_names)
  for i in range(2017,2023):
    corruption_url = 'https://www.transparency.org/en/cpi/{0}'.format(i)
    driver2 = web_driver()
    driver2.get(corruption_url)
    country=class_select(driver2,"flex-1.truncate.pr-2")
    rank =class_select(driver2,"w-16")
    rank.remove('Rank')
    score = class_select(driver2, "font-bold.inline-block.mr-4")
    year = [i] * len(country)
    corruption_table_current = pd.DataFrame(list(zip(country,rank,score,year)),columns= feature_names)
    corruption_table = pd.concat([corruption_table_current,corruption_table])
    i+=1
  return corruption_table

# Corruption table
year_range = range(2017,2023)
corruption_url = 'https://www.transparency.org/en/cpi/{0}'.format(year_range)
country_corruption_df = find_info(corruption_url)